### ISSUE TITLE
Add support for NLO processes

### ISSUE THREAD

**Issue by ajgilbert** [ajgilbert/EFT2Obs#3]
Need to be able to make NLO gridpacks, other than that the commands to generate events will be different.

**Comment by simonepigazzini** [comment]
Hi @ajgilbert,

I worked a bit with SMEFTatNLO starting from your previous repo (EFT2Obs-Demo) to try to get ggH->aa events. I will start working on this in this new repo and let you know if I make any progress.

simone

(In case you are wondering I work CMS Hgg group)

**Comment by ajgilbert** [comment]
Hi Simone, that sounds great, thanks! I'll leave this one for now in any case and work on some of the other issues.

**Comment by ajgilbert** [comment]
Addressed by #17.
